// Generated by CoffeeScript 1.12.6
(function() {
  var amt, cube, doWork, log, square;

  square = function(val) {
    return val * val;
  };

  cube = function(val) {
    return square(val) * val;
  };

  log = function(prefix, message) {
    return console.log(prefix + " " + message);
  };

  doWork = function(amt) {
    var both;
    log("INFO", amt + " squared is " + (square(amt)) + ".");
    log("INFO", amt + " cubed is " + (cube(amt)) + ".");
    both = function(amt) {
      return cube(square(amt));
    };
    return log("INFO", "" + (both(amt)));
  };

  console.log("Loading variable");

  amt = 9;

  console.log("Amount = " + amt);

  console.log("Doing work!");

  doWork(amt);

}).call(this);
