// Generated by CoffeeScript 1.12.6
(function() {
  var myAge, yourAge;

  myAge = 19;

  yourAge = 21;

  if (myAge === yourAge) {
    console.log("We are the same age.");
  } else if (myAge < yourAge) {
    console.log("I am younger.");
  } else if (myAge > yourAge) {
    console.log("You are younger.");
  }

}).call(this);
