// Generated by CoffeeScript 1.12.6
(function() {
  var request;

  request = require('request');

  request('https://httpbin.org/get', function(err, res, body) {
    if (err) {
      return console.log(err);
    } else if (res.statusCode !== 200) {
      return console.log(res.statusCode);
    } else {
      return console.log(body);
    }
  });

}).call(this);
