// Generated by CoffeeScript 1.12.6
(function() {
  var displayLeaders, roster,
    slice = [].slice;

  displayLeaders = function() {
    var first, others, second;
    first = arguments[0], second = arguments[1], others = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    return console.log("1st: " + first + "\n2nd: " + second + "\nOther: [" + others + "]");
  };

  roster = ["jdesive", "ddesive", "adesive", "hdesive", "zdesive"];

  displayLeaders.apply(null, roster);

}).call(this);
