// Generated by CoffeeScript 1.12.6
(function() {
  var Classa;

  Classa = (function() {
    function Classa() {}

    Classa.hello = function() {
      return console.log("Hello from the other class.");
    };

    return Classa;

  })();

  module.exports = Classa;

}).call(this);
